services:
  frontend:
    build:
      context: ./Front
    ports:
      - "3000:80"
    restart: on-failure

  backend:
    build:
      context: ./Backend
      target: runtime
    env_file:
      - Backend/.env
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - database:/app/database
    command: npm start
    restart: on-failure

volumes:
  database:
